import { parser } from "@lezer/python";
import type { SyntaxNode } from "@lezer/common";

const MAX_SOURCE_BYTES = 1024 * 1024;
const MAX_CODE_CHARACTERS = 30_000;
const MAX_REQUEST_BYTES = 64 * 1024;
const FETCH_TIMEOUT_MS = 15_000;
const MAX_CACHE_BYTES = 4 * 1024 * 1024;
const cache = new Map<
  string,
  { bytes: number; source: string; sourceUrl: string }
>();
const inFlight = new Map<
  string,
  Promise<{ source: string; sourceUrl: string }>
>();

interface CandidateContext {
  commitOid: string;
  path: string;
  ref: string;
  repository: string;
  status: "eligible";
  url: string;
}

interface Definition {
  code: string;
  complexity: number;
  endLine: number;
  kind: "function" | "method";
  name: string;
  simpleAccessor: boolean;
  startLine: number;
}

function isSimpleAccessor(node: SyntaxNode, source: string): boolean {
  const body = node.getChild("Body");
  if (!body) return false;
  const statements: SyntaxNode[] = [];
  for (let child = body.firstChild; child; child = child.nextSibling) {
    if (child.name !== ":") statements.push(child);
  }
  while (
    statements[0]?.name === "ExpressionStatement" &&
    statements[0].getChild("String")
  ) {
    statements.shift();
  }
  if (statements.length !== 1 || !statements[0]) return false;
  const statement = source.slice(statements[0].from, statements[0].to).trim();
  return (
    /^return\s+(?:self\.)?[A-Za-z_]\w*$/u.test(statement) ||
    /^(?:self\.)?[A-Za-z_]\w*\s*=\s*(?:self\.)?[A-Za-z_]\w*$/u.test(statement)
  );
}

function collectLineStarts(source: string): number[] {
  const starts = [0];
  for (let index = 0; index < source.length; index += 1) {
    if (source.charCodeAt(index) === 10) starts.push(index + 1);
  }
  return starts;
}

function lineNumber(lineStarts: number[], offset: number): number {
  let low = 0;
  let high = lineStarts.length;
  while (low < high) {
    const middle = Math.floor((low + high) / 2);
    if ((lineStarts[middle] ?? 0) <= offset) low = middle + 1;
    else high = middle;
  }
  return Math.max(1, low);
}

function lineStart(source: string, offset: number): number {
  const newline = source.lastIndexOf("\n", Math.max(0, offset - 1));
  return newline < 0 ? 0 : newline + 1;
}

function containsError(node: SyntaxNode): boolean {
  if (node.type.isError) return true;
  for (let child = node.firstChild; child; child = child.nextSibling) {
    if (containsError(child)) return true;
  }
  return false;
}

function countComplexity(node: SyntaxNode): number {
  const complex = new Set([
    "IfStatement",
    "ForStatement",
    "WhileStatement",
    "TryStatement",
    "WithStatement",
    "MatchStatement",
    "ListComprehension",
    "SetComprehension",
    "DictionaryComprehension",
  ]);
  let score = complex.has(node.name) ? 1 : 0;
  for (let child = node.firstChild; child; child = child.nextSibling) {
    score += countComplexity(child);
  }
  return score;
}

function hasSupportedDecorators(node: SyntaxNode, source: string): boolean {
  if (node.name !== "DecoratedStatement") return true;
  return node
    .getChildren("Decorator")
    .every((decorator) =>
      /^\s*@[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*(?:\([\s\S]*\))?\s*$/u.test(
        source.slice(decorator.from, decorator.to),
      ),
    );
}

function followsRecoveryError(node: SyntaxNode, source: string): boolean {
  let previous = node.prevSibling;
  for (let checked = 0; previous && checked < 2; checked += 1) {
    const gap = source.slice(previous.to, node.from);
    if (/\r?\n\s*\r?\n/u.test(gap)) return false;
    if (containsError(previous)) return true;
    previous = previous.prevSibling;
  }
  return false;
}

function isEligiblePlacement(node: SyntaxNode): "function" | "method" | null {
  const statement =
    node.parent?.name === "DecoratedStatement" ? node.parent : node;
  if (statement.parent?.name === "Script") return "function";
  const classBody = statement.parent;
  if (classBody?.name !== "Body") return null;
  const classDefinition = classBody.parent;
  if (classDefinition?.name !== "ClassDefinition") return null;
  const classStatement =
    classDefinition.parent?.name === "DecoratedStatement"
      ? classDefinition.parent
      : classDefinition;
  return classStatement.parent?.name === "Script" ? "method" : null;
}

export function extractPythonDefinitions(source: string): Definition[] {
  const headerLines: string[] = [];
  for (const line of source.split(/\r?\n/u).slice(0, 20)) {
    if (!/^\s*(?:#|$)/u.test(line)) break;
    headerLines.push(line);
  }
  const header = headerLines.join("\n");
  if (
    /(?:auto[- ]generated|generated (?:file|code)|generated by|do not edit)/iu.test(
      header,
    )
  ) {
    return [];
  }
  const tree = parser.parse(source);
  const lineStarts = collectLineStarts(source);
  const definitions: Definition[] = [];

  function visit(node: SyntaxNode): void {
    if (node.name === "FunctionDefinition") {
      const kind = isEligiblePlacement(node);
      const rangeNode =
        node.parent?.name === "DecoratedStatement" ? node.parent : node;
      const nameNode = node.getChild("VariableName");
      if (
        kind &&
        nameNode &&
        !containsError(rangeNode) &&
        !followsRecoveryError(rangeNode, source)
      ) {
        const from = lineStart(source, rangeNode.from);
        const code = source.slice(from, rangeNode.to);
        if (hasSupportedDecorators(rangeNode, source)) {
          definitions.push({
            code,
            complexity: countComplexity(node),
            endLine: lineNumber(
              lineStarts,
              Math.max(rangeNode.from, rangeNode.to - 1),
            ),
            kind,
            name: source.slice(nameNode.from, nameNode.to),
            simpleAccessor: isSimpleAccessor(node, source),
            startLine: lineNumber(lineStarts, from),
          });
        }
      }
    }
    for (let child = node.firstChild; child; child = child.nextSibling)
      visit(child);
  }

  visit(tree.topNode);
  return definitions;
}

function isUseful(definition: Definition, sourceUrl: string): boolean {
  const lines = definition.code
    .split(/\r?\n/u)
    .filter((line) => line.trim()).length;
  if (lines < 4) return false;
  if (definition.simpleAccessor) return false;
  if (/^(?:get|set|is|has)_[A-Za-z0-9_]+$/u.test(definition.name) && lines <= 5)
    return false;
  if (
    /^\s*(?:async\s+)?def[^:]*:\s*(?:return\s+(?:self\.)?\w+|pass)\s*$/su.test(
      definition.code,
    )
  )
    return false;
  if (/generated (?:file|code)|do not edit/iu.test(definition.code))
    return false;
  if (Array.from(definition.code).length > MAX_CODE_CHARACTERS) return false;
  const request = {
    code: definition.code,
    explanation: "説明",
    language: "python",
    sourceUrl,
  };
  return (
    new TextEncoder().encode(JSON.stringify(request)).byteLength <=
    MAX_REQUEST_BYTES
  );
}

export function selectTrainingCandidates(
  definitions: Definition[],
  sourceUrl: string,
): TrainingCandidate[] {
  const ranked = definitions
    .filter((definition) => isUseful(definition, sourceUrl))
    .map((definition) => ({
      definition,
      score:
        definition.complexity * 5 +
        Math.min(30, definition.code.split(/\r?\n/u).length),
    }))
    .sort(
      (left, right) =>
        left.score - right.score ||
        left.definition.startLine - right.definition.startLine,
    );
  const selected =
    ranked.length <= 3
      ? ranked
      : [
          ranked[0],
          ranked[Math.floor((ranked.length - 1) / 2)],
          ranked.at(-1),
        ].filter((item): item is NonNullable<typeof item> => Boolean(item));
  const levels: TrainingCandidateLevel[] =
    selected.length === 1
      ? ["recommended"]
      : selected.length === 2
        ? ["warmup", "challenge"]
        : ["warmup", "recommended", "challenge"];

  return selected.map(({ definition, score }, index) => {
    const level = levels[index] ?? "recommended";
    const difficulty = score >= 24 ? "上級" : score >= 13 ? "中級" : "初級";
    const estimatedMinutes =
      difficulty === "上級" ? 15 : difficulty === "中級" ? 10 : 5;
    const reason =
      level === "warmup"
        ? "処理の流れを短時間で追いやすく、最初の練習に向いています。"
        : level === "challenge"
          ? "分岐や処理量が比較的多く、丁寧な読解に挑戦できます。"
          : "処理量と分岐のバランスがよく、このファイルを読む練習におすすめです。";
    return {
      code: definition.code,
      difficulty,
      endLine: definition.endLine,
      estimatedMinutes,
      id: `${definition.kind}:${definition.name}:${definition.startLine}`,
      kind: definition.kind,
      level,
      name: definition.name,
      reason,
      sourceUrl,
      startLine: definition.startLine,
    };
  });
}

function parseContext(value: unknown): CandidateContext | null {
  if (!value || typeof value !== "object") return null;
  const context = value as Record<string, unknown>;
  if (
    context.status !== "eligible" ||
    typeof context.repository !== "string" ||
    !/^[^/]{1,100}\/[^/]{1,100}$/u.test(context.repository) ||
    typeof context.ref !== "string" ||
    context.ref.length > 1024 ||
    typeof context.path !== "string" ||
    context.path.length > 4096 ||
    !context.path.endsWith(".py") ||
    context.path
      .split("/")
      .some(
        (part) => !part || part === "." || part === ".." || part.includes("\0"),
      ) ||
    typeof context.commitOid !== "string" ||
    !/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/iu.test(context.commitOid) ||
    typeof context.url !== "string" ||
    context.url.length > 8192
  )
    return null;
  try {
    const url = new URL(context.url);
    const [owner, repository] = context.repository.split("/");
    if (
      url.origin !== "https://github.com" ||
      decodeURIComponent(url.pathname) !==
        `/${owner}/${repository}/blob/${context.ref}/${context.path}`
    )
      return null;
  } catch {
    return null;
  }
  return context as unknown as CandidateContext;
}

function encodedSegments(value: string): string {
  return value.split("/").map(encodeURIComponent).join("/");
}

async function readLimitedResponse(response: Response): Promise<string> {
  if (!response.ok) {
    if (response.status === 403 || response.status === 429)
      throw new Error("RATE_LIMITED");
    if (response.status === 404) throw new Error("NOT_FOUND");
    throw new Error("FETCH_FAILED");
  }
  const declaredLength = Number(response.headers.get("Content-Length"));
  if (Number.isFinite(declaredLength) && declaredLength > MAX_SOURCE_BYTES)
    throw new Error("TOO_LARGE");
  if (response.headers.get("Content-Type")?.includes("application/json")) {
    throw new Error("NOT_FILE");
  }
  let bytes: Uint8Array;
  if (response.body) {
    const reader = response.body.getReader();
    const chunks: Uint8Array[] = [];
    let total = 0;
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      total += value.byteLength;
      if (total > MAX_SOURCE_BYTES) {
        await reader.cancel();
        throw new Error("TOO_LARGE");
      }
      chunks.push(value);
    }
    bytes = new Uint8Array(total);
    let offset = 0;
    for (const chunk of chunks) {
      bytes.set(chunk, offset);
      offset += chunk.byteLength;
    }
  } else {
    bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.byteLength > MAX_SOURCE_BYTES) throw new Error("TOO_LARGE");
  }
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    throw new Error("INVALID_UTF8");
  }
}

async function fetchSource(
  context: CandidateContext,
): Promise<{ source: string; sourceUrl: string }> {
  const key = JSON.stringify([
    context.repository,
    context.commitOid,
    context.path,
  ]);
  const cached = cache.get(key);
  if (cached) {
    cache.delete(key);
    cache.set(key, cached);
    return cached;
  }
  const existing = inFlight.get(key);
  if (existing) return existing;
  const task = (async () => {
    const [owner, repository] = context.repository.split("/");
    const apiUrl = new URL(
      `https://api.github.com/repos/${encodeURIComponent(owner!)}/${encodeURIComponent(repository!)}/contents/${encodedSegments(context.path)}`,
    );
    apiUrl.searchParams.set("ref", context.commitOid);
    const sourceUrl = `https://github.com/${encodeURIComponent(owner!)}/${encodeURIComponent(repository!)}/blob/${context.commitOid}/${encodedSegments(context.path)}`;
    if (sourceUrl.length > 2048) throw new Error("INVALID_SOURCE_URL");
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const response = await fetch(apiUrl, {
        headers: {
          Accept: "application/vnd.github.raw+json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
        signal: controller.signal,
      });
      const source = await readLimitedResponse(response);
      const result = {
        bytes: new TextEncoder().encode(source).byteLength,
        source,
        sourceUrl,
      };
      cache.set(key, result);
      let totalCacheBytes = [...cache.values()].reduce(
        (total, entry) => total + entry.bytes,
        0,
      );
      while (cache.size > 8 || totalCacheBytes > MAX_CACHE_BYTES) {
        const oldestKey = cache.keys().next().value;
        if (!oldestKey) break;
        const oldest = cache.get(oldestKey);
        cache.delete(oldestKey);
        totalCacheBytes -= oldest?.bytes ?? 0;
      }
      return result;
    } finally {
      clearTimeout(timeout);
    }
  })().finally(() => inFlight.delete(key));
  inFlight.set(key, task);
  return task;
}

export async function requestTrainingCandidates(
  contextValue: unknown,
  requestId: string,
): Promise<TrainingCandidatesWorkerResult> {
  const context = parseContext(contextValue);
  const contextKey = context
    ? JSON.stringify([context.repository, context.commitOid, context.path])
    : "invalid";
  if (!context) {
    return {
      contextKey,
      error: {
        code: "INVALID_CONTEXT",
        message: "表示中のcommitを確認できないため、候補を取得できません。",
        retryable: false,
      },
      ok: false,
      requestId,
    };
  }
  try {
    const { source, sourceUrl } = await fetchSource(context);
    return {
      candidates: selectTrainingCandidates(
        extractPythonDefinitions(source),
        sourceUrl,
      ),
      contextKey,
      ok: true,
      requestId,
    };
  } catch (error) {
    const code = error instanceof Error ? error.message : "FETCH_FAILED";
    return {
      contextKey,
      error: {
        code,
        message:
          code === "RATE_LIMITED"
            ? "GitHub APIの利用上限に達したため、候補を取得できません。"
            : "候補を取得できませんでした。",
        retryable: ![
          "INVALID_SOURCE_URL",
          "TOO_LARGE",
          "INVALID_UTF8",
        ].includes(code),
      },
      ok: false,
      requestId,
    };
  }
}
